baseURL = "https://n0nz.github.io"
languageCode = "en-us"
title = "Nonthawat Duangchai"
theme = "minimal"

[params]
    author = "Nonthawat Duangchai"
    description = "Software Engineer working for @KBTG and Counter-Strike: Global Offensive addict."
    copyright = " "
    githubUsername = "n0nz"
    accent = "#005cc5"
    showBorder = true
    backgroundColor = "#e1e4e8"
    font = "Quicksand" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/uses"
    name = "Uses"
    weight = 2

[[menu.main]]
    url = "/cv.pdf"
    name = "CV"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4


[[menu.main]]
    url = "/about"
    name = "About"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:nonthawat.duangchai@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/n0nz/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/nonthawatdc/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/nonthawat-duangchai-9356b9184/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/11347563/nonthawat-duangchai"
    name = "stack-overflow"
    weight = 5

[[menu.icon]]
    url = "https://steamcommunity.com/id/n0nz"
    name = "steam"
    weight = 6
